parameters:

services:
    cabinet.translate_char:
        class: Top10\CabinetBundle\Service\TranslateChar
        arguments: [@service_container]

    cabinet.wiki_text_to_html:
        class: Top10\CabinetBundle\Service\WikiTextToHtml
        arguments: [@service_container]
